functionality:
  name: cajal_run
  namespace: predict_mdality_methods
  
  # metadata for your method
  version: dev
  description: A description for your method.
  authors:
    - name: Anna Laddach
      email: anna.laddach@crick.ac.uk
      roles: [ author, maintainer ]
      props: { github: AnnaLaddach, orcid: "0000-0001-5552-6534" }
    - name: Roman Laddach
      email: roman.laddach@kcl.ac.uk
      roles: [ author, maintainer ]
      props: { github: rladdach, orcid: "0000-0002-0118-4548" }
    - name: Michael Shapiro
      email: michael.shapiro@crick.ac.uk
      roles: [ author, maintainer ]
      props: { github: michaeldshapiro, orcid: "0000-0002-2769-9320" }
      
  # parameters
  arguments:
    # required inputs
    - name: "--input_train_mod1"
      type: "file"
      example: "dataset_mod1.h5ad"
      description: Censored dataset, training cells.
      required: true
    - name: "--input_test_mod1"
      type: "file"
      example: "dataset_mod1.h5ad"
      description: Censored dataset, test cells.
      required: true
    - name: "--input_train_mod2"
      type: "file"
      example: "dataset_mod2.h5ad"
      description: Censored dataset.
      required: true
    - name: "--input_pretrain"
      type: "file"
      example: "pretrain_model"
      description: Path to the directory containing a pretrained model.
      required: true

    # required outputs
    - name: "--output"
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: Dataset with predicted values for modality2.
      required: true
      
    # additional parameters
    - name: "--distance_method"
      type: "string"
      default: "minkowski"
      description: The distance metric to use. Possible values include `euclidean` and `minkowski`.
    - name: "--n_pcs"
      type: "integer"
      default: 50
      description: Number of components to use for dimensionality reduction.
      
  # files your script needs
  resources:
    - type: python_script
      path: script.py
  
  # resources for unit testing your component
  tests:
    - type: python_script
      path: test.py
    - path: ../../../../sample_data/predict_modality/
      dest: sample_data
      
# target platforms
platforms:
  - type: docker
    image: dataintuitive/randpy:py3.8
    setup:
      - type: python
        packages:
          - scikit-learn
          - anndata
          - scanpy
          - tensorflow
          - tensorflow_probability
  - type: nextflow
    labels: [ lowmem, lowtime, lowcpu ]
